### ISSUE TITLE
숙제

### ISSUE THREAD

**Issue by kimkyeongnam** [kimkyeongnam/2019-1.Haesung-Girls-High-School#50]
![캡처](https://user-images.githubusercontent.com/38516906/61054718-fe16ce80-a42a-11e9-9c9e-9d4a3732daa2.PNG)
두 문제 중 하나 이상 풀어서 이슈를 생성해주세요.
숙제 제출은
1. 한 화면에 코드 및 실행결과를 캡쳐하거나 
2. 코드 내용 그대로 복사하여 붙여넣거나
3. 파일 자체를 업로드 

해주세요.

---

### 예시 1)
이름: **홍길동**
![캡처](https://user-images.githubusercontent.com/38516906/61055184-e68c1580-a42b-11e9-9436-3b55f85eba89.PNG)
<br>

### 예시 2)
이름: **홍길동**
* 코드
```
a=2
b=3

print(a+b)
```
* 실행결과 
```
5
```
<br>

### 예시 3)
이름: **홍길동**
[example.zip](https://github.com/kimkyeongnam/2019-1.Haesung-Girls-High-School/files/3382245/example.zip)

---
질문사항은 Issue #3 댓글로 문의바랍니다. 모두 화이팅~ ٩(●ᴗ●)۶

**Comment by parkdonghee1129** [comment]
만약 문제를 다 못 풀겠으면 미완성인채로 내도 괜찮아요. 
"코드는 어떤식으로 짤려고 노력했는데 어떤 부분이 어려워서 못했다. "
이런식으로 설명이랑 같이 내주세요.
